<?php

namespace App\Controller\Admin;

use App\Entity\Appartement;
use App\Form\AppartementType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\File\Exception\FileException;

/**
 * @Route("admin/appartement")
 */
class AppartementController extends AbstractController
{
    /**
     * @Route("/", name="admin_appartement_index", methods={"GET"})
     */
    public function index(): Response
    {
        $appartements = $this->getDoctrine()
            ->getRepository(Appartement::class)
            ->findAll();

        return $this->render('admin/appartement/index.html.twig', [
            'appartements' => $appartements,
        ]);
    }

    /**
     * @Route("/new", name="admin_appartement_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $appartement = new Appartement();
        $form = $this->createForm(AppartementType::class, $appartement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            //************** file upload ***>>>>>>>>>>>>
            /** @var file $file */ /* -> je dois ajouter * ici */
             $file = $form['image']->getData();
            if ($file) {
                $fileName = $this->generateUniqueFileName() . '.' . $file->guessExtension();
                // Move the file to the directory where brochures are stored
                try {
                    $file->move(
                        $this->getParameter('kernel.project_dir') . '/public/uploads',  // in Servis.yaml defined folder for upload images
                        $fileName
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }

                $appartement->setImage($fileName); // Related upload file name with Hotel table image field
            } 
            //<<<<<<<<<<<<<<<<<******** file upload ***********>

            $entityManager->persist($appartement);
            $entityManager->flush();

            return $this->redirectToRoute('admin_appartement_index');
        }

        return $this->render('admin/appartement/new.html.twig', [
            'appartement' => $appartement,
            'form' => $form->createView(),
        ]);
    }
    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
    /**
     * @Route("/{id}", name="admin_appartement_show", methods={"GET"})
     */
    public function show(Appartement $appartement): Response
    {
        return $this->render('admin/appartement/show.html.twig', [
            'appartement' => $appartement,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="admin_appartement_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Appartement $appartement): Response
    {
        $form = $this->createForm(AppartementType::class, $appartement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            /** @var file $file */ /* -> je dois ajouter * ici */
            $file = $form['image']->getData();
            if ($file) {
                $fileName = $this->generateUniqueFileName() . '.' . $file->guessExtension();
                // Move the file to the directory where brochures are stored
                try {
                    $file->move(
                        $this->getParameter('kernel.project_dir') . '/public/uploads',  // Servis.yaml de tanımladığımız resim yolu
                        $fileName
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }
                $appartement->setImage($fileName);
            }


            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('admin_appartement_index');
        }

        return $this->render('admin/appartement/edit.html.twig', [
            'appartement' => $appartement,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="admin_appartement_delete", methods={"DELETE"})
     * @param Request $request
     * @param Appartement $appartement
     * @return Response
     */
    public function delete(Request $request, Appartement $appartement): Response
    {
        if ($this->isCsrfTokenValid('delete'.$appartement->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($appartement);
            $entityManager->flush();
        }

        return $this->redirectToRoute('admin_appartement_index');
    }
}
